- name: install zsh and plugins
  homebrew:
    name: ['zsh', 'zsh-syntax-highlighting', 'zsh-completions']
    state: present

- name: deploy ~/.zshrc
  copy:
    src: .zshrc
    dest: ~/.zshrc
    mode: 0644
