- name: add PATH for zsh
  block:
    - name: add PATH
      blockinfile:
        dest: ~/.zprofile
        insertafter: '^# PATH'
        content: 'export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"'

    - name: reload profile
      shell: source ~/.zprofile

  when:
    - use_zsh

- name: add PATH for bash
  block:
    - name: add PATH
      blockinfile:
        dest: ~/.bash_profile
        insertafter: '^# PATH'
        content: 'export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"'

    - name: reload profile
      shell: source ~/.bash_profile

  when:
    - not use_zsh

- name: install extentions
  shell: "code --install-extension {{ item }}"
  with_items:
    - coenraads.bracket-pair-colorizer
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-spring-initializr
    - pivotal.vscode-boot-dev-pack
    - pivotal.vscode-spring-boot
    - georgewfraser.vscode-javac
    - ithildir.java-properties
    - rianadon.vscode-java-checkstyle
    - shengchen.vscode-checkstyle
    - gabrielbb.vscode-lombok
    - vscjava.vscode-java-debug
    - ms-azuretools.vscode-docker
    - dbaeumer.vscode-eslint
    - donjayamanne.githistory
    - eamodio.gitlens
    - oderwat.indent-rainbow
    - pverest.java-ide-pack
    - xabikos.javascriptsnippets
    - ms-vsliveshare.vsliveshare
    - shd101wyy.markdown-preview-enhanced
    - gicentre.markdown-preview-enhanced-with-litvis
    - pkief.material-icon-theme
    - vscjava.vscode-maven
    - christian-kohler.npm-intellisense
    - jebbs.plantuml
    - esbenp.prettier-vscode
    - alefragnani.project-manager
    - shardulm94.trailing-spaces
    - octref.vetur
    - visualstudioexptteam.vscodeintellicode
    - hollowtree.vue-snippets
    - sdras.vue-vscode-extensionpack
    - sdras.vue-vscode-snippets
    - redhat.vscode-xml
    - redhat.vscode-yaml

- name: deploy settings.json
  template:
    src: settings.json.j2
    dest: '~/Library/Application Support/Code/User/settings.json'
    mode: 0644
    backup: yes

- name: deploy keybindings.json
  copy:
    src: keybindings.json
    dest: '~/Library/Application Support/Code/User/keybindings.json'
    mode: 0644
    backup: yes
